import AGENT_GUIDELINES from "./agent-guidelines.md";

const CLAUDE_GUIDELINES = AGENT_GUIDELINES;
const CURSOR_GUIDELINES = AGENT_GUIDELINES;
const GEMINI_GUIDELINES = AGENT_GUIDELINES;
const COPILOT_GUIDELINES = AGENT_GUIDELINES;

const README_GUIDELINES = `## AI Agent Guidelines\n\n${AGENT_GUIDELINES.replace(/^#.*\n/, "")}`;

export {
	AGENT_GUIDELINES,
	CLAUDE_GUIDELINES,
	CURSOR_GUIDELINES,
	GEMINI_GUIDELINES,
	COPILOT_GUIDELINES,
	README_GUIDELINES,
};
